[tool.black]
line-length = 79
include = '\.py'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | \.venv
  | \.vscode
  | __pycache__
  | _build
  | buck-out
  | build
  | dist
  | venv
)/
'''
